// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJbZxRYud9YZmWuEI24HzS9ryyBNuc6I',
    appId: '1:13045535088:web:e42c11ca9fbaec64463fb5',
    messagingSenderId: '13045535088',
    projectId: 'vesuvius-f8dee',
    authDomain: 'vesuvius-f8dee.firebaseapp.com',
    storageBucket: 'vesuvius-f8dee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9PIn9rPej8l0KDWdzBZr1jIvXy0w7zuk',
    appId: '1:13045535088:android:279abc90d22bbe7e463fb5',
    messagingSenderId: '13045535088',
    projectId: 'vesuvius-f8dee',
    storageBucket: 'vesuvius-f8dee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvxVwGWgEby3gsfAH7BN9sBlACll53EoA',
    appId: '1:13045535088:ios:2e3c2b7f635809a0463fb5',
    messagingSenderId: '13045535088',
    projectId: 'vesuvius-f8dee',
    storageBucket: 'vesuvius-f8dee.firebasestorage.app',
    iosBundleId: 'com.example.appvesuvius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvxVwGWgEby3gsfAH7BN9sBlACll53EoA',
    appId: '1:13045535088:ios:2e3c2b7f635809a0463fb5',
    messagingSenderId: '13045535088',
    projectId: 'vesuvius-f8dee',
    storageBucket: 'vesuvius-f8dee.firebasestorage.app',
    iosBundleId: 'com.example.appvesuvius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJbZxRYud9YZmWuEI24HzS9ryyBNuc6I',
    appId: '1:13045535088:web:eead001323e5a7c9463fb5',
    messagingSenderId: '13045535088',
    projectId: 'vesuvius-f8dee',
    authDomain: 'vesuvius-f8dee.firebaseapp.com',
    storageBucket: 'vesuvius-f8dee.firebasestorage.app',
  );
}
